### PR TITLE
body is the new #newtab-scrollbox

### PR DESCRIPTION
**Pull request by xabolcs**
In recent Firefoxes the New Tab was redesigned, and got a new ID.

I updated the MozCamp extension to search for that ID.

Please review!

### CODE REVIEW

**Comment by xabolcs** [comment]
Should I keep compatibility for older Firefox?

I happily update all other New Tab extensions.

**Comment by xabolcs** [comment]
`#newtab-vertical-margin` is not perfect. :(

**Comment by diegocr** [comment]
Thank you!

What problem(s) did you found using `#newtab-vertical-margin`? I use the Skeedz extension and it looks fine using that.

I'll make a tiny script to update all other NewTab extensions so don't worry about that :)

**Comment by diegocr** [comment]
Er, just noticed you submitted this more than a month ago, i completely missed it, sorry :$

**Comment by xabolcs** [comment]
> Er, just noticed you submitted this more than a month ago, i completely missed it, sorry :$

And now it have merge conflicts. ;) No problem, thanks for accepting!

Will provide a freshing commit soon here.

**Comment by xabolcs** [comment]
> What problem(s) did you found using `#newtab-vertical-margin`? I use the Skeedz extension and it looks fine using that.

Hmmm, I don't remember exactly, but I got repeated background on the bottom.
Closing this until I find a good STR. :)

**Comment by diegocr** [comment]
> Will provide a freshing commit soon here.

Not needed really, sorry, on 4bac874e67289b0fc3ae6f11af73d6b159db2fb8 i've already upgraded all extensions by using `#newtab-vertical-margin`, there is some other similar extension which also fixed compatibility to Fx 42+ by adding that, and it looked fine in these here too, so i did it that way as well :)

**Comment by diegocr** [comment]
> I don't remember exactly, but I got repeated background on the bottom.

Interesting, i think the css rule `background-size: cover;` should prevent that, since the image must cover the whole browser window, perhaps you had installed another newtab-related-extension messing around?

**Comment by xabolcs** [comment]
> perhaps you had installed another newtab-related-extension messing around?

Just yours! :D 

I don't know what happened. I'll leave a comment here, if I found something.

**Comment by diegocr** [comment]
:smile:  :+1: 

Thanks for everything :)

**Pull request closed without merging**
